'use client';

import { useMemo, useState } from 'react';
import Sidebar from '../components/Sidebar';
import { useDashboardData, type ChangeRecord } from '../components/DashboardDataProvider';

type SortKey = 'project' | 'field' | 'previous' | 'current' | 'category';
const columns = ['Project', 'Business unit', 'Project type', 'Field changed', 'Previous value', 'New value', 'Category', 'Significant'];
const escapeCsv = (value: string) => `"${value.replace(/"/g, '""')}"`;
function download(content: string, name: string, type: string) { const url = URL.createObjectURL(new Blob([content], { type })); const link = document.createElement('a'); link.href = url; link.download = name; link.click(); URL.revokeObjectURL(url); }

export default function ChangesPage() {
  const { changes, snapshotDate: baselineDate, projects } = useDashboardData();
  const [sortKey, setSortKey] = useState<SortKey>('project'); const [descending, setDescending] = useState(false);
  const fileNameDate = new Date(baselineDate).toISOString().slice(0, 10);
  const sortedChanges = useMemo(() => [...changes].sort((left, right) => { const result = left[sortKey].localeCompare(right[sortKey], undefined, { numeric: true, sensitivity: 'base' }); return descending ? -result : result; }), [changes, sortKey, descending]);
  const sortBy = (key: SortKey) => { if (key === sortKey) setDescending(value => !value); else { setSortKey(key); setDescending(false); } };
  const sortLabel = (key: SortKey, label: string) => <button type="button" onClick={() => sortBy(key)} aria-label={`Sort by ${label}`}>{label} {sortKey === key ? (descending ? '↓' : '↑') : '↕'}</button>;
  const exportCsv = () => download([columns.join(','), ...sortedChanges.map(change => [change.project, change.unit, change.projectType, change.field, change.previous, change.current, change.category, change.significant ? 'Yes' : 'No'].map(escapeCsv).join(','))].join('\n'), `PMO-Change-Log-${fileNameDate}.csv`, 'text/csv;charset=utf-8');
  const exportExcel = () => { const rows = sortedChanges.map(change => `<tr><td>${change.project}</td><td>${change.unit}</td><td>${change.projectType}</td><td>${change.field}</td><td>${change.previous}</td><td>${change.current}</td><td>${change.category}</td><td>${change.significant ? 'Yes' : 'No'}</td></tr>`).join('') || '<tr><td colspan="8">Baseline established — no changes have been captured yet.</td></tr>'; download(`<!doctype html><html><head><meta charset="utf-8"><style>table{border-collapse:collapse;font-family:Arial}th,td{border:1px solid #ccd7d5;padding:8px;text-align:left}th{background:#e6f1ef;color:#146e70}</style></head><body><h1>PMO Change Log</h1><p>Baseline snapshot: ${baselineDate}</p><table><thead><tr>${columns.map(column => `<th>${column}</th>`).join('')}</tr></thead><tbody>${rows}</tbody></table></body></html>`, `PMO-Change-Log-${fileNameDate}.xls`, 'application/vnd.ms-excel'); };
  const exportWord = () => { const items = sortedChanges.length ? `<ol>${sortedChanges.map(change => `<li><strong>${change.project}</strong> — ${change.field}: ${change.previous} → ${change.current}</li>`).join('')}</ol>` : `<p>No changes have been captured yet. The current ${baselineDate} snapshot is the baseline for the next import.</p>`; download(`<!doctype html><html><head><meta charset="utf-8"><style>body{font-family:Arial;color:#18252c;margin:42px}h1{color:#146e70}p{line-height:1.5}</style></head><body><h1>PMO Change Log</h1><p><strong>Baseline snapshot:</strong> ${baselineDate}</p><p><strong>Changes captured:</strong> ${changes.length}</p>${items}</body></html>`, `PMO-Change-Log-${fileNameDate}.doc`, 'application/msword'); };
  return <main className="with-sidebar changes-page"><Sidebar /><div className="page-content"><header className="portfolio-top"><span>PMO / Changes</span><span>Baseline: {baselineDate}</span></header><section className="changes-hero"><div><p className="eyebrow">SNAPSHOT HISTORY</p><h1>Portfolio change log</h1><p>Changes are recorded whenever a newly imported project and Flash-report pair is compared with the prior snapshot.</p></div><div className="change-export-actions"><button onClick={exportExcel}>Export Excel</button><button onClick={exportCsv}>Export CSV</button><button onClick={exportWord}>Export Word</button></div></section><section className="changes-summary"><article><span>Current baseline</span><strong>{baselineDate}</strong><small>{projects.length} portfolio projects</small></article><article><span>Comparison available</span><strong>{changes.length}</strong><small>{changes.length ? 'changes recorded' : 'Awaiting next snapshot'}</small></article><article><span>Export includes</span><strong>8 fields</strong><small>Previous and new values</small></article></section><section className="change-log"><div className="change-log-heading">{sortLabel('project', 'Project')}{sortLabel('field', 'Field changed')}{sortLabel('previous', 'Previous value')}{sortLabel('current', 'New value')}{sortLabel('category', 'Category')}</div>{sortedChanges.length ? sortedChanges.map(change => <article key={`${change.project}-${change.field}`}><strong>{change.project}</strong><span>{change.field}</span><span>{change.previous}</span><span>{change.current}</span><span className={change.significant ? 'significant-change' : ''}>{change.category}</span></article>) : <div className="empty-changes"><span>⇄</span><strong>Baseline established</strong><p>Import the next project and Flash report exports to generate the first comparison.</p></div>}</section></div></main>;
}
