'use client';
import { FormEvent, type CSSProperties, useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { reportsByProject } from './flashReports';
import { portfolioProjects } from './portfolioData';

type Health = 'At risk' | 'Off track';
const projects = [
  { name: 'SalesForce Field Services Module', owner: 'Paul McCabe', health: 'At risk' as Health, progress: 83, milestone: 'Execution · Apr 13, 2026', variance: 'High priority' },
  { name: 'Order Entry Migration to Salesforce', owner: 'Michelle Tipton', health: 'At risk' as Health, progress: 47, milestone: 'Requirements · Sep 18, 2026', variance: 'Trend down' },
  { name: 'Factory Track V7.x Implementation', owner: 'Amber Porter', health: 'At risk' as Health, progress: 80, milestone: 'Initiation · Jan 14, 2027', variance: 'Medium priority' },
  { name: 'AP Automation - Medius Implementation', owner: 'Jennifer Peterson', health: 'Off track' as Health, progress: 75, milestone: 'Design · Oct 09, 2026', variance: 'Trend down' },
  { name: 'New IT Build - VAN 6 Manufacturing', owner: 'Easton Korver', health: 'Off track' as Health, progress: 85, milestone: 'Execution · Oct 30, 2026', variance: 'Highest priority' },
  { name: 'New IT Build - Ridgeland, MS', owner: 'Easton Korver', health: 'Off track' as Health, progress: 52, milestone: 'Execution · Oct 09, 2026', variance: 'High priority' },
  { name: 'Mechanical Design Scheduling', owner: 'Jennifer Peterson', health: 'Off track' as Health, progress: 74, milestone: 'Initiation · Aug 31, 2026', variance: 'Medium priority' },
  { name: 'Vendor Master Data Clean-up', owner: 'Jennifer Peterson', health: 'Off track' as Health, progress: 27, milestone: 'Initiation · Jan 26, 2027', variance: 'Medium priority' },
  { name: 'IEM - PIU Vision Inspection Development', owner: 'Jennifer Peterson', health: 'Off track' as Health, progress: 42, milestone: 'Initiation · Jan 27, 2027', variance: 'Medium priority' },
  { name: 'Simplify SOLI Process', owner: 'Michelle Tipton', health: 'Off track' as Health, progress: 38, milestone: 'Initiation · Jan 15, 2027', variance: 'Medium priority' },
  { name: 'The Work Number Implementation', owner: 'Easton Korver', health: 'At risk' as Health, progress: 37, milestone: 'Initiation · Dec 04, 2026', variance: 'On hold' },
];
const healthClass: Record<Health, string> = { 'At risk': 'risk', 'Off track': 'watch' };
const healthRank: Record<Health, number> = { 'At risk': 0, 'Off track': 1 };
const statusByProjectName = new Map(portfolioProjects.map(project => [project.name, project.status]));
const targetWindow = (target: string) => { const date = new Date(target); const period = date.getDate() <= 10 ? 'Early' : date.getDate() <= 20 ? 'Mid' : 'Late'; return `${period} ${['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'][date.getMonth()]} ${date.getFullYear()}`; };
const targetWindowByProjectName = new Map(portfolioProjects.map(project => [project.name, targetWindow(project.target)]));

export default function Home() {
  const [filter, setFilter] = useState<'All' | Health>('All');
  const [messages, setMessages] = useState([{ role: 'assistant', text: 'Good morning, Kevin. The August 25 portfolio export has 11 initiatives needing attention: 4 at risk and 7 off track. I can prepare a steering summary, surface risks, or answer questions about a project.' }]);
  const [question, setQuestion] = useState('');
  const [selected, setSelected] = useState('SalesForce Field Services Module');
  const [defaultProject, setDefaultProject] = useState('SalesForce Field Services Module');
  const [detailOpen, setDetailOpen] = useState(false);
  const [agentWidth, setAgentWidth] = useState(365);
  const [historyWidth, setHistoryWidth] = useState(340);
  useEffect(() => { if ('serviceWorker' in navigator) navigator.serviceWorker.register('/sw.js').catch(() => undefined); const savedProject = window.localStorage.getItem('pmo-agent-default-project'); if (savedProject && portfolioProjects.some(project => project.name === savedProject)) { setSelected(savedProject); setDefaultProject(savedProject); } }, []);
  const visible = useMemo(() => (filter === 'All' ? projects : projects.filter(p => p.health === filter)).slice().sort((a, b) => healthRank[a.health] - healthRank[b.health] || a.name.localeCompare(b.name)), [filter]);
  function askAgent(event: FormEvent) { event.preventDefault(); const prompt = question.trim(); if (!prompt) return; const lower = prompt.toLowerCase(); const scoped = projects.map(item => portfolioProjects.find(project => project.name === item.name)).filter((project): project is NonNullable<typeof project> => Boolean(project)); const missing = scoped.filter(project => !(reportsByProject[project.name]?.length)); let response: string;
    if (/(missing|no flash|without flash)/.test(lower)) response = missing.length ? `Projects without Flash reports:\n${missing.map(project => `• ${project.name}`).join('\n')}` : 'All at-risk and off-track projects have a Flash report on file.';
    else if (/\bhighlights?\b/.test(lower)) { const highlights = scoped.map(project => ({ project, highlight: reportsByProject[project.name]?.[0]?.highlights })).filter(item => item.highlight?.trim()); response = highlights.length ? `Latest Flash report highlights:\n${highlights.map(({ project, highlight }) => `• ${project.name} — ${highlight}`).join('\n')}` : 'The latest Flash reports for these projects do not list any highlights.'; }
    else if (/\bissues?\b/.test(lower)) { const issues = scoped.map(project => ({ project, issue: reportsByProject[project.name]?.[0]?.issues })).filter(item => item.issue?.trim()); response = issues.length ? `Latest Flash report issues:\n${issues.map(({ project, issue }) => `• ${project.name} — ${issue}`).join('\n')}` : 'The latest Flash reports for these projects do not list any issues.'; }
    else if (/(at risk|off track|risk)/.test(lower)) response = `Projects needing attention:\n${scoped.map(project => `• ${project.name} — ${project.health}; ${project.status}; ${project.phase}; ${project.progress}% complete`).join('\n')}`;
    else if (/(hold|in progress|ready|status)/.test(lower)) { const status = ['On hold', 'In progress', 'Ready'].find(value => lower.includes(value.toLowerCase())); const matches = status ? scoped.filter(project => project.status === status) : scoped; response = `Matching attention projects:\n${matches.map(project => `• ${project.name} — ${project.status}; ${project.health}; target ${targetWindow(project.target)}`).join('\n')}`; }
    else response = `Attention portfolio summary:\n• ${scoped.filter(project => project.health === 'At risk').length} at risk projects\n• ${scoped.filter(project => project.health === 'Off track').length} off-track projects\n• ${scoped.filter(project => project.status === 'On hold').length} on hold\n\nAsk about status, risks, issues, highlights, target dates, or missing Flash reports.`;
    setMessages(current => [...current, { role: 'user', text: prompt }, { role: 'assistant', text: response }]); setQuestion(''); }
  function setAgentDefault() { window.localStorage.setItem('pmo-agent-default-project', selected); setDefaultProject(selected); }
  return <main className={`app-shell ${detailOpen ? 'details-open' : ''}`} style={{ '--agent-width': `${agentWidth}px`, '--history-width': `${historyWidth}px` } as CSSProperties}>
    <aside className="sidebar"><div className="brand"><span className="brand-mark">IT</span><span>PORTFOLIO</span></div><nav aria-label="Primary navigation"><a className="nav-item active" href="#overview"><span>▦</span>Overview</a><Link className="nav-item" href="/portfolio"><span>◫</span>Portfolio</Link><Link className="nav-item" href="/roadmap"><span>⌁</span>Roadmap</Link><Link className="nav-item" href="/reports"><span>▤</span>Data</Link></nav><div className="sidebar-bottom"><div className="agent-pulse">✦</div><div><strong>PMO Agent</strong><small>Portfolio intelligence</small></div></div></aside>
    <section className="workspace" id="overview"><header className="topbar"><div className="crumb">PMO / <strong>Executive overview</strong></div><div className="top-actions"><button className="icon-button" aria-label="Notifications">◌<i /></button><button className="avatar" aria-label="User menu">KH</button></div></header><div className="content">
      <section className="hero"><div><p className="eyebrow">TUESDAY, AUGUST 25, 2026</p><h1>Portfolio health, at a glance.</h1><p className="lede">Updated from the August 25 project portfolio and Flash reporting exports.</p></div></section>
      <section className="metrics" aria-label="Portfolio health summary"><article><span className="metric-label">Active initiatives</span><strong>93</strong><span className="subtle">73 in progress · 16 on hold</span></article><article><span className="metric-label">On track</span><strong className="positive">82</strong><span className="subtle">88% of portfolio</span></article><article><span className="metric-label">Needs attention</span><strong className="warning">11</strong><span className="subtle">4 at risk · 7 off track</span></article><article><span className="metric-label">Latest Flash reports</span><strong>74</strong><span className="subtle">From 188 report snapshots</span></article></section>
      <section className="portfolio-section" id="portfolio"><div className="section-heading"><div><p className="eyebrow">PORTFOLIO PULSE</p><h2>Projects requiring your attention</h2></div><div className="filters">{(['All', 'At risk', 'Off track'] as const).map(item => <button key={item} className={filter === item ? 'selected' : ''} onClick={() => setFilter(item)}>{item}</button>)}</div></div><div className="project-list">{visible.map(project => <button key={project.name} className={`project-row ${selected === project.name ? 'focused' : ''}`} onClick={() => { setSelected(project.name); setDetailOpen(true); }}><span className={`status-dot ${healthClass[project.health]}`} /><span className="project-main"><strong>{project.name}</strong><small>Owner · {project.owner}</small></span><span className="project-progress"><span><b>{project.progress}%</b> complete</span><em><i style={{ width: `${project.progress}%` }} /></em></span><span className={`health-badge ${healthClass[project.health]}`}>{project.health}</span><span className="milestone"><small>Target completion</small><b>{targetWindowByProjectName.get(project.name) ?? '—'}</b></span><span className="variance">{statusByProjectName.get(project.name) ?? '—'}</span></button>)}</div></section>
    </div></section><div className="resize-handle" role="separator" aria-orientation="vertical" aria-label="Resize PMO Agent" onPointerDown={event => { event.currentTarget.setPointerCapture(event.pointerId); const move = (pointerEvent: PointerEvent) => setAgentWidth(Math.min(480, Math.max(220, pointerEvent.clientX - 228))); const stop = () => { window.removeEventListener('pointermove', move); window.removeEventListener('pointerup', stop); }; window.addEventListener('pointermove', move); window.addEventListener('pointerup', stop); }} />
    <aside className="copilot" aria-label="PMO AI Agent"><header><div><span className="copilot-icon">✦</span><div><strong>PMO Agent</strong><small>Attention portfolio</small></div></div></header><div className="copilot-context"><span>Agent context</span><strong>11 projects needing attention</strong><small>4 at risk · 7 off track</small><small>Scoped to these projects only.</small></div><div className="chat">{messages.map((message, index) => <div key={index} className={`message ${message.role}`}><span>{message.role === 'assistant' ? '✦' : 'KH'}</span><p>{message.text}</p></div>)}</div><form onSubmit={askAgent}><label className="chat-input"><input value={question} onChange={event => setQuestion(event.target.value)} placeholder="Ask about attention projects…" aria-label="Ask PMO Agent" /><button type="submit" aria-label="Send message">↑</button></label><small className="disclaimer">Agent uses at-risk and off-track portfolio data only.</small></form></aside>{detailOpen && <div className="history-resize" role="separator" aria-orientation="vertical" aria-label="Resize Flash report details" onPointerDown={event => { event.currentTarget.setPointerCapture(event.pointerId); const move = (pointerEvent: PointerEvent) => setHistoryWidth(Math.min(700, Math.max(280, window.innerWidth - pointerEvent.clientX))); const stop = () => { window.removeEventListener('pointermove', move); window.removeEventListener('pointerup', stop); }; window.addEventListener('pointermove', move); window.addEventListener('pointerup', stop); }} />}{detailOpen && <aside className="main-history"><ProjectHistory projectName={selected} onClose={() => setDetailOpen(false)} /></aside>}
  </main>;
}

function ProjectHistory({ projectName, onClose }: { projectName: string; onClose: () => void }) {
  const reports = reportsByProject[projectName] ?? [];
  return <div className="project-history"><header><div><p className="eyebrow">FLASH REPORT HISTORY</p><strong>{projectName}</strong><small>Most recent report first · up to five reports</small></div><button onClick={onClose} aria-label="Return to PMO Agent">×</button></header>{reports.length === 0 ? <div className="empty-history"><span>◌</span><strong>No Flash reports on file</strong><p>This project has no matching report history in the August 25 Flash export.</p></div> : <div className="history-scroll">{reports.map((report, index) => <article className="report-card" key={`${report.date}-${index}`}><div className="report-head"><div><span className="report-sequence">{index === 0 ? 'LATEST' : `REPORT ${index + 1}`}</span><strong>{report.date}</strong></div><div><span className={`health-badge ${report.health === 'Off track' ? 'watch' : report.health === 'At risk' ? 'risk' : 'good'}`}>{report.health}</span><small>{report.complete ?? '—'}% complete</small></div></div><ReportField label="Summary" text={report.summary} /><ReportField label="Highlights" text={report.highlights} /><ReportField label="Issues" text={report.issues} /><ReportField label="Next steps" text={report.nextSteps} /></article>)}</div>}</div>;
}

function ReportField({ label, text }: { label: string; text: string }) {
  return text ? <div className="report-field"><span>{label}</span><p>{text}</p></div> : null;
}
